language: go

go:
  - 1.9.x

install:
  - make install

script:
  # build test for supported platforms
  - GOOS=linux go build
  - GOOS=darwin go build
  - GOOS=freebsd go build
  - GOARCH=386 go build

  - make test
